const subscriptions = [
    {
      name: "Calisthenics base",
      type: "mensile",
      price: "€40",
      id: "1",
    },
    {
      name: "Calisthenics base",
      type: "trimestrale",
      price: "€110",
      id: "1",
    },
    {
      name: "Calisthenics base",
      type: "semestrale",
      price: "€210",
      id: "1",
    },
    {
      name: "Calisthenics base",
      type: "annuale",
      price: "€410",
      id: "1",
    },
    {
      name: "Calisthenics intermedio",
      type: "mensile",
      price: "€40",
      id: "2",
    },
    {
      name: "Calisthenics intermedio",
      type: "trimestrale",
      price: "€110",
      id: "2",
    },
    {
      name: "Calisthenics intermedio",
      type: "semestrale",
      price: "€210",
      id: "2",
    },
    {
      name: "Calisthenics intermedio",
      type: "annuale",
      price: "€410",
      id: "2",
    },
    {
      name: "Calisthenics avanzato",
      type: "mensile",
      price: "€40",
      id: "3",
    },
    {
      name: "Calisthenics avanzato",
      type: "trimestrale",
      price: "€110",
      id: "3",
    },
    {
      name: "Calisthenics avanzato",
      type: "semestrale",
      price: "€210",
      id: "3",
    },
    {
      name: "Calisthenics avanzato",
      type: "annuale",
      price: "price 3",
      id: "3",
    },
    {
      name: "Power yoga base",
      type: "mensile",
      price: "€40",
      id: "4",
    },
    {
      name: "Power yoga base",
      type: "trimestrale",
      price: "€110",
      id: "4",
    },
    {
      name: "Power yoga base",
      type: "semestrale",
      price: "€210",
      id: "4",
    },
    {
      name: "Power yoga base",
      type: "annuale",
      price: "€410",
      id: "4",
    },
    {
      name: "Power yoga intermedio",
      type: "mensile",
      price: "€40",
      id: "5",
    },
    {
      name: "Power yoga intermedio",
      type: "trimestrale",
      price: "€110",
      id: "5",
    },
    {
      name: "Power yoga intermedio",
      type: "semestrale",
      price: "€210",
      id: "5",
    },
    {
      name: "Power yoga intermedio",
      type: "annuale",
      price: "€410",
      id: "5",
    },
    {
      name: "Power yoga avanzato",
      type: "mensile",
      price: "€40",
      id: "6",
    },
    {
      name: "Power yoga avanzato",
      type: "trimestrale",
      price: "€110",
      id: "6",
    },
    {
      name: "Power yoga avanzato",
      type: "semestrale",
      price: "€210",
      id: "6",
    },
    {
      name: "Power yoga avanzato",
      type: "annuale",
      price: "€410",
      id: "6",
    },
    {
      name: "Bodybuilding base",
      type: "mensile",
      price: "€40",
      id: "7",
    },
    {
      name: "Bodybuilding base",
      type: "trimestrale",
      price: "€110",
      id: "7",
    },
    {
      name: "Bodybuilding base",
      type: "semestrale",
      price: "€210",
      id: "7",
    },
    {
      name: "Bodybuilding base",
      type: "annuale",
      price: "€410",
      id: "7",
    },
    {
      name: "Bodybuilding intermedio",
      type: "mensile",
      price: "€40",
      id: "7",
    },
    {
      name: "Bodybuilding intermedio",
      type: "trimestrale",
      price: "€110",
      id: "7",
    },
    {
      name: "Bodybuilding intermedio",
      type: "semestrale",
      price: "€210",
      id: "7",
    },
    {
      name: "Bodybuilding intermedio",
      type: "annuale",
      price: "€410",
      id: "7",
    },
  
    {
      name: "Bodybuilding avanzato",
      type: "mensile",
      price: "€40",
      id: "7",
    },
    {
      name: "Bodybuilding avanzato",
      type: "trimestrale",
      price: "€110",
      id: "7",
    },
    {
      name: "Bodybuilding avanzato",
      type: "semestrale",
      price: "€210",
      id: "7",
    },
    {
      name: "Bodybuilding avanzato",
      type: "annuale",
      price: "€410",
      id: "7",
    },
    {
      name: "Calisthenics + Power yoga",
      type: "mensile",
      price: "€55",
      id: "7",
    },
    {
      name: "Calisthenics + Power yoga",
      type: "trimestrale",
      price: "€160",
      id: "7",
    },
    {
      name: "Calisthenics + Power yoga",
      type: "semestrale",
      price: "€210",
      id: "7",
    },
    {
      name: "Calisthenics + Power yoga",
      type: "annuale",
      price: "€610",
      id: "7",
    },
    {
      name: "Calisthenics + Bodybuilding",
      type: "mensile",
      price: "€55",
      id: "7",
    },
    {
      name: "Calisthenics + Bodybuilding",
      type: "trimestrale",
      price: "€160",
      id: "7",
    },
    {
      name: "Calisthenics + Bodybuilding",
      type: "semestrale",
      price: "€310",
      id: "7",
    },
    {
      name: "Calisthenics + Bodybuilding",
      type: "annuale",
      price: "€610",
      id: "7",
    },
    {
      name: "Power yoga + Bodybuilding",
      type: "mensile",
      price: "€55",
      id: "7",
    },
    {
      name: "Power yoga + Bodybuilding",
      type: "trimestrale",
      price: "€160",
      id: "7",
    },
    {
      name: "Power yoga + Bodybuilding",
      type: "semestrale",
      price: "€310",
      id: "7",
    },
    {
      name: "Power yoga + Bodybuilding",
      type: "annuale",
      price: "€610",
      id: "7",
    },
    {
      name: "Calisthenics + Power yoga + Bodybuilding",
      type: "mensile",
      price: "€90",
      id: "7",
    },
    {
      name: "Calisthenics + Power yoga + Bodybuilding",
      type: "trimestrale",
      price: "€260",
      id: "7",
    },
    {
      name: "Calisthenics + Power yoga + Bodybuilding",
      type: "semestrale",
      price: "€500",
      id: "7",
    },
    {
      name: "Calisthenics + Power yoga + Bodybuilding",
      type: "annuale",
      price: "€980",
      id: "7",
    },
  ];
  
  export default subscriptions;
  